// Automatically generated by python/export_dashboard_data.py
window.DASHBOARD_DATA = {
  "kpis": {
    "total_sales": 2961669.95,
    "total_profit": 423672.35,
    "margin": 14.305184478776914,
    "total_orders": 5486,
    "total_qty": 12219,
    "aov": 539.8596336128327,
    "avg_discount": 9.735690849434926,
    "total_customers": 642
  },
  "monthly": {
    "labels": [
      "2023-01",
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11",
      "2023-12",
      "2024-01",
      "2024-02",
      "2024-03",
      "2024-04",
      "2024-05",
      "2024-06",
      "2024-07",
      "2024-08",
      "2024-09",
      "2024-10",
      "2024-11",
      "2024-12"
    ],
    "sales": [
      78161.95,
      88458.5,
      82307.05,
      108087.3,
      114377.6,
      81361.95,
      89691.75,
      92784.6,
      107982.5,
      98467.5,
      293443.2,
      275009.05,
      88062.4,
      92946.9,
      108955.8,
      79743.4,
      74218.9,
      99767.25,
      102259.8,
      99050.5,
      63254.25,
      87823.95,
      289078.75,
      266375.1
    ],
    "profit": [
      11281.95,
      12325.5,
      7607.05,
      17548.3,
      15169.6,
      12556.95,
      14058.75,
      15730.6,
      15724.5,
      13194.9,
      39773.2,
      40523.05,
      12803.4,
      13122.9,
      17293.8,
      11108.4,
      10404.9,
      14729.25,
      14895.8,
      14151.5,
      5909.25,
      9321.95,
      44694.75,
      39742.1
    ],
    "orders": [
      176,
      171,
      151,
      207,
      191,
      158,
      166,
      186,
      181,
      170,
      509,
      498,
      153,
      163,
      193,
      158,
      175,
      153,
      187,
      169,
      156,
      174,
      513,
      528
    ]
  },
  "regional": {
    "labels": [
      "North",
      "East",
      "South",
      "West",
      "Central"
    ],
    "sales": [
      885892.95,
      666463.9,
      536556.6,
      525522.85,
      347233.65
    ],
    "profit": [
      121270.95,
      99733.9,
      75266.0,
      75324.85,
      52076.65
    ],
    "margin": [
      13.69,
      14.96,
      14.03,
      14.33,
      15.0
    ],
    "orders": [
      1640,
      1199,
      1029,
      998,
      620
    ],
    "customers": [
      299,
      287,
      275,
      270,
      194
    ]
  },
  "category": {
    "labels": [
      "Furniture",
      "Office Supplies",
      "Technology"
    ],
    "sales": [
      1110094.0,
      110774.7,
      1740801.25
    ],
    "profit": [
      -27331.0,
      43326.1,
      407677.25
    ],
    "margin": [
      -2.46,
      39.11,
      23.42
    ]
  },
  "payment": {
    "labels": [
      "Credit Card",
      "UPI",
      "Debit Card",
      "Net Banking",
      "Cash on Delivery"
    ],
    "counts": [
      2156,
      1328,
      1116,
      505,
      381
    ]
  },
  "top_products": [
    {
      "id": "TEC-LP-1002",
      "category": "Technology",
      "sales": 675420.0,
      "profit": 132720.0,
      "margin": 19.65,
      "units": 603
    },
    {
      "id": "TEC-PH-1001",
      "category": "Technology",
      "sales": 581357.5,
      "profit": 149357.5,
      "margin": 25.69,
      "units": 720
    },
    {
      "id": "FUR-SF-2005",
      "category": "Furniture",
      "sales": 413725.0,
      "profit": -16665.0,
      "margin": -4.03,
      "units": 757
    },
    {
      "id": "FUR-TB-2002",
      "category": "Furniture",
      "sales": 274545.0,
      "profit": -18735.0,
      "margin": -6.82,
      "units": 752
    },
    {
      "id": "TEC-MN-1003",
      "category": "Technology",
      "sales": 218055.0,
      "profit": 56775.0,
      "margin": 26.04,
      "units": 768
    },
    {
      "id": "FUR-DS-2004",
      "category": "Furniture",
      "sales": 173952.0,
      "profit": -2328.0,
      "margin": -1.34,
      "units": 678
    },
    {
      "id": "TEC-PR-1005",
      "category": "Technology",
      "sales": 170387.5,
      "profit": 33207.5,
      "margin": 19.49,
      "units": 722
    },
    {
      "id": "FUR-BK-2003",
      "category": "Furniture",
      "sales": 129756.0,
      "profit": 3581.0,
      "margin": 2.76,
      "units": 721
    },
    {
      "id": "FUR-CH-2001",
      "category": "Furniture",
      "sales": 118116.0,
      "profit": 6816.0,
      "margin": 5.77,
      "units": 795
    },
    {
      "id": "TEC-HD-1006",
      "category": "Technology",
      "sales": 70185.5,
      "profit": 23355.5,
      "margin": 33.28,
      "units": 669
    }
  ],
  "bottom_products": [
    {
      "id": "FUR-TB-2002",
      "category": "Furniture",
      "sales": 274545.0,
      "profit": -18735.0,
      "margin": -6.82,
      "units": 752
    },
    {
      "id": "FUR-SF-2005",
      "category": "Furniture",
      "sales": 413725.0,
      "profit": -16665.0,
      "margin": -4.03,
      "units": 757
    },
    {
      "id": "FUR-DS-2004",
      "category": "Furniture",
      "sales": 173952.0,
      "profit": -2328.0,
      "margin": -1.34,
      "units": 678
    },
    {
      "id": "OFF-EN-3005",
      "category": "Office Supplies",
      "sales": 5434.8,
      "profit": 3247.8,
      "margin": 59.76,
      "units": 729
    },
    {
      "id": "FUR-BK-2003",
      "category": "Furniture",
      "sales": 129756.0,
      "profit": 3581.0,
      "margin": 2.76,
      "units": 721
    },
    {
      "id": "OFF-LA-3006",
      "category": "Office Supplies",
      "sales": 10102.5,
      "profit": 5041.5,
      "margin": 49.9,
      "units": 723
    },
    {
      "id": "OFF-BI-3002",
      "category": "Office Supplies",
      "sales": 10316.4,
      "profit": 5229.8,
      "margin": 50.69,
      "units": 833
    },
    {
      "id": "OFF-PA-3001",
      "category": "Office Supplies",
      "sales": 11925.0,
      "profit": 5535.0,
      "margin": 46.42,
      "units": 710
    },
    {
      "id": "FUR-CH-2001",
      "category": "Furniture",
      "sales": 118116.0,
      "profit": 6816.0,
      "margin": 5.77,
      "units": 795
    },
    {
      "id": "OFF-ST-3003",
      "category": "Office Supplies",
      "sales": 17461.25,
      "profit": 7017.25,
      "margin": 40.19,
      "units": 746
    }
  ],
  "discount_sensitivity": {
    "labels": [
      "0-5%",
      "6-15%",
      "16-25%",
      "26-35%",
      ">35%"
    ],
    "avg_profit": [
      134.29,
      91.76,
      -8.21,
      -87.86,
      -206.23
    ],
    "total_profit": [
      410264.65,
      101211.0,
      -6103.5,
      -28905.8,
      -52794.0
    ],
    "orders": [
      3055,
      1103,
      743,
      329,
      256
    ],
    "loss_rate": [
      0.1,
      0.0,
      37.0,
      72.3,
      100.0
    ]
  },
  "customer_segments": {
    "labels": [
      "Regular",
      "High Value",
      "Dormant / Low Engagement",
      "At Risk",
      "New"
    ],
    "counts": [
      342,
      156,
      97,
      41,
      6
    ],
    "spend": [
      905921.9,
      1759095.95,
      107594.1,
      188549.2,
      508.8
    ],
    "avg_recency": [
      36.9,
      17.9,
      280.3,
      215.7,
      24.3
    ]
  },
  "at_risk_customers": [
    {
      "id": "CUST-0149",
      "type": "Corporate",
      "region": "Central",
      "orders": 3,
      "spend": 15789.0,
      "profit": 289.0,
      "days_inactive": 212,
      "action": "Immediate VIP Call"
    },
    {
      "id": "CUST-0062",
      "type": "Small Business",
      "region": "North",
      "orders": 9,
      "spend": 13356.35,
      "profit": 2584.35,
      "days_inactive": 202,
      "action": "Immediate VIP Call"
    },
    {
      "id": "CUST-0427",
      "type": "Consumer",
      "region": "East",
      "orders": 8,
      "spend": 9208.5,
      "profit": -777.5,
      "days_inactive": 133,
      "action": "Immediate VIP Call"
    },
    {
      "id": "CUST-0509",
      "type": "Consumer",
      "region": "North",
      "orders": 8,
      "spend": 8866.5,
      "profit": 1574.5,
      "days_inactive": 366,
      "action": "Immediate VIP Call"
    },
    {
      "id": "CUST-0008",
      "type": "Consumer",
      "region": "South",
      "orders": 7,
      "spend": 8135.0,
      "profit": 1981.0,
      "days_inactive": 163,
      "action": "Immediate VIP Call"
    },
    {
      "id": "CUST-0627",
      "type": "Consumer",
      "region": "East",
      "orders": 7,
      "spend": 6258.0,
      "profit": 514.0,
      "days_inactive": 136,
      "action": "Immediate VIP Call"
    },
    {
      "id": "CUST-0233",
      "type": "Consumer",
      "region": "East",
      "orders": 7,
      "spend": 5783.0,
      "profit": 1093.0,
      "days_inactive": 367,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0384",
      "type": "Small Business",
      "region": "West",
      "orders": 2,
      "spend": 5400.0,
      "profit": 1380.0,
      "days_inactive": 134,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0099",
      "type": "Consumer",
      "region": "East",
      "orders": 6,
      "spend": 5365.5,
      "profit": 867.5,
      "days_inactive": 225,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0544",
      "type": "Consumer",
      "region": "West",
      "orders": 6,
      "spend": 5136.0,
      "profit": 1113.0,
      "days_inactive": 376,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0310",
      "type": "Corporate",
      "region": "Central",
      "orders": 4,
      "spend": 5115.0,
      "profit": -409.0,
      "days_inactive": 183,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0250",
      "type": "Corporate",
      "region": "Central",
      "orders": 4,
      "spend": 5102.5,
      "profit": 1205.5,
      "days_inactive": 389,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0351",
      "type": "Small Business",
      "region": "East",
      "orders": 5,
      "spend": 5089.25,
      "profit": 662.25,
      "days_inactive": 220,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0362",
      "type": "Small Business",
      "region": "Central",
      "orders": 4,
      "spend": 4745.55,
      "profit": 1113.55,
      "days_inactive": 237,
      "action": "Automated 15% Win-Back Email"
    },
    {
      "id": "CUST-0322",
      "type": "Consumer",
      "region": "South",
      "orders": 6,
      "spend": 4745.5,
      "profit": 805.5,
      "days_inactive": 136,
      "action": "Automated 15% Win-Back Email"
    }
  ],
  "scatter_customers": [
    {
      "id": "CUST-0087",
      "x": 58,
      "y": 6691.25,
      "segment": "High Value"
    },
    {
      "id": "CUST-0196",
      "x": 36,
      "y": 12291.7,
      "segment": "High Value"
    },
    {
      "id": "CUST-0486",
      "x": 35,
      "y": 3622.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0625",
      "x": 301,
      "y": 733.4,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0073",
      "x": 156,
      "y": 1930.2,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0598",
      "x": 24,
      "y": 7048.3,
      "segment": "High Value"
    },
    {
      "id": "CUST-0235",
      "x": 21,
      "y": 12313.2,
      "segment": "High Value"
    },
    {
      "id": "CUST-0567",
      "x": 120,
      "y": 32.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0405",
      "x": 25,
      "y": 2694.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0472",
      "x": 6,
      "y": 863.3,
      "segment": "Regular"
    },
    {
      "id": "CUST-0169",
      "x": 115,
      "y": 3296.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0307",
      "x": 30,
      "y": 6739.8,
      "segment": "High Value"
    },
    {
      "id": "CUST-0618",
      "x": 25,
      "y": 530.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0082",
      "x": 46,
      "y": 408.7,
      "segment": "Regular"
    },
    {
      "id": "CUST-0266",
      "x": 148,
      "y": 2638.5,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0533",
      "x": 51,
      "y": 6487.75,
      "segment": "High Value"
    },
    {
      "id": "CUST-0503",
      "x": 15,
      "y": 786.7,
      "segment": "Regular"
    },
    {
      "id": "CUST-0301",
      "x": 185,
      "y": 835.5,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0070",
      "x": 25,
      "y": 4067.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0011",
      "x": 15,
      "y": 8380.5,
      "segment": "High Value"
    },
    {
      "id": "CUST-0252",
      "x": 30,
      "y": 3105.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0064",
      "x": 21,
      "y": 2678.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0464",
      "x": 13,
      "y": 18852.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0055",
      "x": 1,
      "y": 14384.2,
      "segment": "High Value"
    },
    {
      "id": "CUST-0535",
      "x": 3,
      "y": 14336.1,
      "segment": "High Value"
    },
    {
      "id": "CUST-0283",
      "x": 1,
      "y": 2212.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0530",
      "x": 28,
      "y": 3364.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0102",
      "x": 10,
      "y": 1373.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0119",
      "x": 17,
      "y": 6823.3,
      "segment": "High Value"
    },
    {
      "id": "CUST-0032",
      "x": 20,
      "y": 6725.1,
      "segment": "High Value"
    },
    {
      "id": "CUST-0286",
      "x": 28,
      "y": 2865.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0056",
      "x": 2,
      "y": 3517.4,
      "segment": "Regular"
    },
    {
      "id": "CUST-0344",
      "x": 7,
      "y": 3624.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0269",
      "x": 100,
      "y": 2563.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0551",
      "x": 2,
      "y": 1935.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0180",
      "x": 38,
      "y": 16438.75,
      "segment": "High Value"
    },
    {
      "id": "CUST-0109",
      "x": 358,
      "y": 373.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0430",
      "x": 7,
      "y": 6951.3,
      "segment": "High Value"
    },
    {
      "id": "CUST-0212",
      "x": 26,
      "y": 2260.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0111",
      "x": 2,
      "y": 10694.4,
      "segment": "High Value"
    },
    {
      "id": "CUST-0165",
      "x": 106,
      "y": 1135.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0289",
      "x": 228,
      "y": 3625.5,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0110",
      "x": 34,
      "y": 685.1,
      "segment": "Regular"
    },
    {
      "id": "CUST-0077",
      "x": 30,
      "y": 1364.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0508",
      "x": 6,
      "y": 4233.7,
      "segment": "Regular"
    },
    {
      "id": "CUST-0003",
      "x": 202,
      "y": 3568.7,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0584",
      "x": 1,
      "y": 1119.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0273",
      "x": 3,
      "y": 21945.3,
      "segment": "High Value"
    },
    {
      "id": "CUST-0363",
      "x": 2,
      "y": 8323.8,
      "segment": "High Value"
    },
    {
      "id": "CUST-0265",
      "x": 1,
      "y": 9515.45,
      "segment": "High Value"
    },
    {
      "id": "CUST-0646",
      "x": 119,
      "y": 855.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0303",
      "x": 21,
      "y": 2166.05,
      "segment": "Regular"
    },
    {
      "id": "CUST-0178",
      "x": 53,
      "y": 5090.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0147",
      "x": 3,
      "y": 7727.55,
      "segment": "High Value"
    },
    {
      "id": "CUST-0031",
      "x": 7,
      "y": 467.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0449",
      "x": 17,
      "y": 5670.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0559",
      "x": 1,
      "y": 11604.75,
      "segment": "High Value"
    },
    {
      "id": "CUST-0216",
      "x": 15,
      "y": 2863.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0045",
      "x": 16,
      "y": 1888.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0167",
      "x": 56,
      "y": 934.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0079",
      "x": 24,
      "y": 14062.5,
      "segment": "High Value"
    },
    {
      "id": "CUST-0185",
      "x": 183,
      "y": 1667.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0595",
      "x": 122,
      "y": 1144.4,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0224",
      "x": 412,
      "y": 790.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0609",
      "x": 14,
      "y": 19937.2,
      "segment": "High Value"
    },
    {
      "id": "CUST-0282",
      "x": 26,
      "y": 12987.5,
      "segment": "High Value"
    },
    {
      "id": "CUST-0352",
      "x": 109,
      "y": 1019.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0435",
      "x": 265,
      "y": 4061.7,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0582",
      "x": 156,
      "y": 1167.1,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0638",
      "x": 185,
      "y": 2951.9,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0066",
      "x": 369,
      "y": 800.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0347",
      "x": 49,
      "y": 902.1,
      "segment": "Regular"
    },
    {
      "id": "CUST-0050",
      "x": 23,
      "y": 4053.4,
      "segment": "Regular"
    },
    {
      "id": "CUST-0261",
      "x": 325,
      "y": 3715.0,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0254",
      "x": 30,
      "y": 5646.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0040",
      "x": 23,
      "y": 2284.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0239",
      "x": 181,
      "y": 3121.6,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0369",
      "x": 40,
      "y": 3668.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0007",
      "x": 20,
      "y": 6301.5,
      "segment": "High Value"
    },
    {
      "id": "CUST-0439",
      "x": 52,
      "y": 4634.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0091",
      "x": 40,
      "y": 4203.4,
      "segment": "Regular"
    },
    {
      "id": "CUST-0497",
      "x": 17,
      "y": 2743.35,
      "segment": "Regular"
    },
    {
      "id": "CUST-0608",
      "x": 6,
      "y": 1515.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0462",
      "x": 31,
      "y": 4927.1,
      "segment": "Regular"
    },
    {
      "id": "CUST-0418",
      "x": 8,
      "y": 7709.1,
      "segment": "High Value"
    },
    {
      "id": "CUST-0637",
      "x": 13,
      "y": 13471.8,
      "segment": "High Value"
    },
    {
      "id": "CUST-0157",
      "x": 2,
      "y": 16556.55,
      "segment": "High Value"
    },
    {
      "id": "CUST-0556",
      "x": 415,
      "y": 1187.5,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0605",
      "x": 7,
      "y": 14671.85,
      "segment": "High Value"
    },
    {
      "id": "CUST-0367",
      "x": 6,
      "y": 18887.25,
      "segment": "High Value"
    },
    {
      "id": "CUST-0536",
      "x": 255,
      "y": 2991.3,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0042",
      "x": 4,
      "y": 3743.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0438",
      "x": 16,
      "y": 1293.4,
      "segment": "Regular"
    },
    {
      "id": "CUST-0432",
      "x": 158,
      "y": 739.2,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0057",
      "x": 53,
      "y": 2533.65,
      "segment": "Regular"
    },
    {
      "id": "CUST-0575",
      "x": 29,
      "y": 3408.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0133",
      "x": 11,
      "y": 900.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0270",
      "x": 1,
      "y": 16829.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0581",
      "x": 16,
      "y": 988.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0647",
      "x": 0,
      "y": 12429.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0025",
      "x": 29,
      "y": 1922.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0231",
      "x": 20,
      "y": 4305.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0132",
      "x": 15,
      "y": 3193.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0501",
      "x": 16,
      "y": 11073.5,
      "segment": "High Value"
    },
    {
      "id": "CUST-0446",
      "x": 212,
      "y": 1115.7,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0083",
      "x": 14,
      "y": 4887.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0480",
      "x": 55,
      "y": 2775.1,
      "segment": "Regular"
    },
    {
      "id": "CUST-0160",
      "x": 25,
      "y": 1710.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0078",
      "x": 311,
      "y": 866.5,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0523",
      "x": 47,
      "y": 7781.5,
      "segment": "High Value"
    },
    {
      "id": "CUST-0071",
      "x": 5,
      "y": 6193.05,
      "segment": "High Value"
    },
    {
      "id": "CUST-0394",
      "x": 21,
      "y": 5584.05,
      "segment": "Regular"
    },
    {
      "id": "CUST-0249",
      "x": 39,
      "y": 2328.1,
      "segment": "Regular"
    },
    {
      "id": "CUST-0208",
      "x": 54,
      "y": 2246.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0388",
      "x": 48,
      "y": 2773.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0061",
      "x": 22,
      "y": 10342.8,
      "segment": "High Value"
    },
    {
      "id": "CUST-0136",
      "x": 24,
      "y": 6063.7,
      "segment": "High Value"
    },
    {
      "id": "CUST-0370",
      "x": 23,
      "y": 2791.15,
      "segment": "Regular"
    },
    {
      "id": "CUST-0334",
      "x": 41,
      "y": 2858.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0255",
      "x": 17,
      "y": 12840.4,
      "segment": "High Value"
    },
    {
      "id": "CUST-0620",
      "x": 33,
      "y": 5505.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0134",
      "x": 244,
      "y": 611.5,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0217",
      "x": 26,
      "y": 19421.8,
      "segment": "High Value"
    },
    {
      "id": "CUST-0442",
      "x": 254,
      "y": 1126.85,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0376",
      "x": 26,
      "y": 9179.3,
      "segment": "High Value"
    },
    {
      "id": "CUST-0181",
      "x": 38,
      "y": 1032.7,
      "segment": "Regular"
    },
    {
      "id": "CUST-0525",
      "x": 1,
      "y": 2539.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0518",
      "x": 55,
      "y": 1425.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0333",
      "x": 404,
      "y": 1174.2,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0030",
      "x": 20,
      "y": 1208.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0150",
      "x": 3,
      "y": 6852.35,
      "segment": "High Value"
    },
    {
      "id": "CUST-0621",
      "x": 95,
      "y": 5702.8,
      "segment": "Regular"
    },
    {
      "id": "CUST-0214",
      "x": 5,
      "y": 856.8,
      "segment": "Regular"
    },
    {
      "id": "CUST-0304",
      "x": 42,
      "y": 6076.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0381",
      "x": 17,
      "y": 4213.7,
      "segment": "Regular"
    },
    {
      "id": "CUST-0323",
      "x": 102,
      "y": 6238.35,
      "segment": "High Value"
    },
    {
      "id": "CUST-0325",
      "x": 11,
      "y": 9973.55,
      "segment": "High Value"
    },
    {
      "id": "CUST-0490",
      "x": 49,
      "y": 4138.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0291",
      "x": 30,
      "y": 2157.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0606",
      "x": 19,
      "y": 3580.8,
      "segment": "Regular"
    },
    {
      "id": "CUST-0580",
      "x": 58,
      "y": 682.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0310",
      "x": 183,
      "y": 5115.0,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0610",
      "x": 19,
      "y": 5679.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0316",
      "x": 30,
      "y": 4036.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0613",
      "x": 50,
      "y": 1368.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0305",
      "x": 727,
      "y": 12.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0240",
      "x": 59,
      "y": 227.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0360",
      "x": 48,
      "y": 3651.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0105",
      "x": 33,
      "y": 4553.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0115",
      "x": 3,
      "y": 4011.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0602",
      "x": 75,
      "y": 986.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0331",
      "x": 9,
      "y": 1646.4,
      "segment": "Regular"
    },
    {
      "id": "CUST-0008",
      "x": 163,
      "y": 8135.0,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0294",
      "x": 346,
      "y": 838.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0471",
      "x": 18,
      "y": 5166.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0337",
      "x": 40,
      "y": 3315.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0457",
      "x": 91,
      "y": 2131.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0440",
      "x": 16,
      "y": 6888.9,
      "segment": "High Value"
    },
    {
      "id": "CUST-0341",
      "x": 126,
      "y": 3887.0,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0366",
      "x": 69,
      "y": 1089.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0141",
      "x": 6,
      "y": 11847.2,
      "segment": "High Value"
    },
    {
      "id": "CUST-0215",
      "x": 4,
      "y": 13715.15,
      "segment": "High Value"
    },
    {
      "id": "CUST-0044",
      "x": 38,
      "y": 4144.8,
      "segment": "Regular"
    },
    {
      "id": "CUST-0043",
      "x": 28,
      "y": 9844.35,
      "segment": "High Value"
    },
    {
      "id": "CUST-0074",
      "x": 0,
      "y": 5204.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0332",
      "x": 21,
      "y": 12707.25,
      "segment": "High Value"
    },
    {
      "id": "CUST-0565",
      "x": 45,
      "y": 5257.7,
      "segment": "Regular"
    },
    {
      "id": "CUST-0067",
      "x": 30,
      "y": 2123.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0012",
      "x": 5,
      "y": 9574.75,
      "segment": "High Value"
    },
    {
      "id": "CUST-0437",
      "x": 10,
      "y": 7755.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0564",
      "x": 48,
      "y": 1791.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0315",
      "x": 39,
      "y": 2456.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0631",
      "x": 39,
      "y": 2700.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0262",
      "x": 394,
      "y": 1395.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0368",
      "x": 289,
      "y": 4215.4,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0242",
      "x": 44,
      "y": 11224.7,
      "segment": "High Value"
    },
    {
      "id": "CUST-0387",
      "x": 197,
      "y": 2191.6,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0084",
      "x": 42,
      "y": 2288.35,
      "segment": "Regular"
    },
    {
      "id": "CUST-0588",
      "x": 26,
      "y": 2060.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0634",
      "x": 9,
      "y": 23330.65,
      "segment": "High Value"
    },
    {
      "id": "CUST-0401",
      "x": 8,
      "y": 15295.95,
      "segment": "High Value"
    },
    {
      "id": "CUST-0080",
      "x": 22,
      "y": 4493.55,
      "segment": "Regular"
    },
    {
      "id": "CUST-0024",
      "x": 1,
      "y": 2924.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0346",
      "x": 320,
      "y": 1114.75,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0338",
      "x": 24,
      "y": 17385.25,
      "segment": "High Value"
    },
    {
      "id": "CUST-0222",
      "x": 17,
      "y": 8464.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0238",
      "x": 60,
      "y": 3945.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0326",
      "x": 8,
      "y": 8140.3,
      "segment": "High Value"
    },
    {
      "id": "CUST-0489",
      "x": 28,
      "y": 1822.95,
      "segment": "Regular"
    },
    {
      "id": "CUST-0443",
      "x": 55,
      "y": 609.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0138",
      "x": 27,
      "y": 312.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0579",
      "x": 301,
      "y": 933.6,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0494",
      "x": 3,
      "y": 18261.95,
      "segment": "High Value"
    },
    {
      "id": "CUST-0203",
      "x": 11,
      "y": 4302.1,
      "segment": "Regular"
    },
    {
      "id": "CUST-0213",
      "x": 8,
      "y": 3393.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0010",
      "x": 0,
      "y": 7352.4,
      "segment": "High Value"
    },
    {
      "id": "CUST-0604",
      "x": 11,
      "y": 593.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0516",
      "x": 38,
      "y": 2459.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0420",
      "x": 28,
      "y": 1416.45,
      "segment": "Regular"
    },
    {
      "id": "CUST-0636",
      "x": 13,
      "y": 2721.7,
      "segment": "Regular"
    },
    {
      "id": "CUST-0296",
      "x": 45,
      "y": 2139.45,
      "segment": "Regular"
    },
    {
      "id": "CUST-0085",
      "x": 28,
      "y": 3896.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0297",
      "x": 315,
      "y": 807.5,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0219",
      "x": 43,
      "y": 2242.35,
      "segment": "Regular"
    },
    {
      "id": "CUST-0207",
      "x": 49,
      "y": 1395.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0200",
      "x": 6,
      "y": 9793.75,
      "segment": "High Value"
    },
    {
      "id": "CUST-0279",
      "x": 195,
      "y": 476.4,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0094",
      "x": 52,
      "y": 3130.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0264",
      "x": 169,
      "y": 2785.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0225",
      "x": 38,
      "y": 2261.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0593",
      "x": 378,
      "y": 1930.0,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0029",
      "x": 48,
      "y": 1046.2,
      "segment": "Regular"
    },
    {
      "id": "CUST-0188",
      "x": 30,
      "y": 12843.1,
      "segment": "High Value"
    },
    {
      "id": "CUST-0524",
      "x": 13,
      "y": 1280.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0182",
      "x": 33,
      "y": 509.6,
      "segment": "Regular"
    },
    {
      "id": "CUST-0427",
      "x": 133,
      "y": 9208.5,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0155",
      "x": 30,
      "y": 2616.1,
      "segment": "Regular"
    },
    {
      "id": "CUST-0076",
      "x": 223,
      "y": 1285.3,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0359",
      "x": 218,
      "y": 3508.5,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0093",
      "x": 105,
      "y": 1840.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0355",
      "x": 49,
      "y": 8132.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0069",
      "x": 2,
      "y": 18785.65,
      "segment": "High Value"
    },
    {
      "id": "CUST-0317",
      "x": 2,
      "y": 11309.4,
      "segment": "High Value"
    },
    {
      "id": "CUST-0521",
      "x": 115,
      "y": 900.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0192",
      "x": 23,
      "y": 1724.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0016",
      "x": 189,
      "y": 902.8,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0373",
      "x": 17,
      "y": 9073.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0614",
      "x": 32,
      "y": 3012.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0089",
      "x": 20,
      "y": 2220.75,
      "segment": "Regular"
    },
    {
      "id": "CUST-0546",
      "x": 60,
      "y": 4222.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0118",
      "x": 6,
      "y": 3375.0,
      "segment": "Regular"
    },
    {
      "id": "CUST-0458",
      "x": 39,
      "y": 2857.05,
      "segment": "Regular"
    },
    {
      "id": "CUST-0487",
      "x": 142,
      "y": 3939.0,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0034",
      "x": 49,
      "y": 4602.4,
      "segment": "Regular"
    },
    {
      "id": "CUST-0001",
      "x": 171,
      "y": 3565.0,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0643",
      "x": 17,
      "y": 582.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0253",
      "x": 157,
      "y": 1519.15,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0413",
      "x": 99,
      "y": 2128.4,
      "segment": "Regular"
    },
    {
      "id": "CUST-0557",
      "x": 9,
      "y": 3262.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0591",
      "x": 84,
      "y": 221.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0410",
      "x": 0,
      "y": 2415.25,
      "segment": "Regular"
    },
    {
      "id": "CUST-0023",
      "x": 3,
      "y": 12661.05,
      "segment": "High Value"
    },
    {
      "id": "CUST-0062",
      "x": 202,
      "y": 13356.35,
      "segment": "At Risk"
    },
    {
      "id": "CUST-0117",
      "x": 9,
      "y": 6026.1,
      "segment": "High Value"
    },
    {
      "id": "CUST-0454",
      "x": 68,
      "y": 2067.5,
      "segment": "Regular"
    },
    {
      "id": "CUST-0232",
      "x": 10,
      "y": 5224.9,
      "segment": "Regular"
    },
    {
      "id": "CUST-0090",
      "x": 16,
      "y": 6911.0,
      "segment": "High Value"
    },
    {
      "id": "CUST-0186",
      "x": 55,
      "y": 8374.7,
      "segment": "High Value"
    },
    {
      "id": "CUST-0276",
      "x": 143,
      "y": 2099.5,
      "segment": "Dormant / Low Engagement"
    },
    {
      "id": "CUST-0495",
      "x": 17,
      "y": 2784.0,
      "segment": "Regular"
    }
  ],
  "ai_insights": [
    {
      "title": "Regional Contraction in South Territory",
      "tag": "Geographic Demand Drag",
      "severity": "critical",
      "fact": "In H2 2024, South Region sales dropped by -19.53% (-$40,423.70 delta) and operating profit plunged by -43.85%. The primary contraction was driven by Technology hardware (-41.82%).",
      "explanation": "Competitor regional hub launch or elongated B2B procurement budget cycles in Southern IT centers. Fulfillment lead-time delays in local carrier networks.",
      "investigation": "Audit last 6 months of Southern B2B lost-deal notes and cross-reference on-time delivery rates with carrier logs.",
      "action": "Deploy targeted regional trade-in promotions for hardware and initiate executive outreach with top 25 southern accounts."
    },
    {
      "title": "Severe Margin Destruction on Discounts >= 25%",
      "tag": "Pricing & Margin Leakage",
      "severity": "high",
      "fact": "Furniture operated at an overall margin of -2.46% (net loss of -$27,331.00). 100% of orders with discounts >= 25% operated at an outright negative operating profit.",
      "explanation": "Discretionary discounting permitted by sales reps to meet gross volume targets without visibility into thin wholesale base margins on conference tables.",
      "investigation": "Review CRM discount approval logs to isolate which sales reps and customer tiers consistently exceed 20% discount rates.",
      "action": "Enforce a strict 20% automated discount ceiling in the e-commerce checkout and align rep bonuses with gross margin dollars rather than revenue."
    },
    {
      "title": "High-Value Account Dormancy (>120 Days Inactivity)",
      "tag": "Customer Retention Exposure",
      "severity": "warning",
      "fact": "41 mature accounts have surpassed the 120-day inactivity threshold (average dormancy: 215.6 days), placing $188,689.85 in proven historical revenue at risk of churn.",
      "explanation": "Lack of automated lifecycle notifications and absence of proactive account manager touchpoints following peak holiday ordering.",
      "investigation": "Scan helpdesk tickets for unresolved delivery or quality disputes among the 41 at-risk accounts.",
      "action": "Trigger automated Day-90 replenishment workflows and assign dedicated account executives to personally reach out to the top 10 dormant accounts."
    }
  ],
  "ml_models": [
    {
      "name": "7-Day Naive Persistence",
      "type": "Baseline Benchmark",
      "mae": 3480.66,
      "rmse": 5335.03,
      "r2": -0.128,
      "description": "Assumes tomorrow's revenue equals sales from exactly 7 days prior. Used as standard naive benchmark."
    },
    {
      "name": "Linear Regression",
      "type": "Parametric Baseline",
      "mae": 3005.65,
      "rmse": 4259.62,
      "r2": 0.281,
      "description": "Standard multiple linear regression on lag features and calendar signals."
    },
    {
      "name": "Random Forest Regressor (Production)",
      "type": "Non-Linear Ensemble",
      "mae": 3113.27,
      "rmse": 4058.42,
      "r2": 0.347,
      "description": "100-tree ensemble with max_depth=8 and min_samples_leaf=3. Captures non-linear holiday spikes."
    }
  ],
  "ml_features": [
    {
      "feature": "Sales_Rolling_7_Mean",
      "importance": 0.428,
      "description": "7-day backward moving average of daily revenue"
    },
    {
      "feature": "Sales_Lag_7",
      "importance": 0.185,
      "description": "Exact sales revenue from 7 days ago (day-of-week seasonality)"
    },
    {
      "feature": "Sales_Rolling_14_Mean",
      "importance": 0.142,
      "description": "14-day medium-term trend line"
    },
    {
      "feature": "Sales_Lag_1",
      "importance": 0.089,
      "description": "Prior day's immediate sales momentum"
    },
    {
      "feature": "Is_Q4_Holiday",
      "importance": 0.067,
      "description": "Binary indicator for high-volume Nov-Dec holiday shopping surge"
    },
    {
      "feature": "Day_of_Week",
      "importance": 0.038,
      "description": "Weekly cyclical shopping patterns (Mon-Sun)"
    },
    {
      "feature": "Sales_Rolling_7_Std",
      "importance": 0.027,
      "description": "7-day rolling revenue volatility"
    },
    {
      "feature": "Month",
      "importance": 0.024,
      "description": "Annual seasonality progression (1-12)"
    }
  ],
  "validation_tests": [
    {
      "name": "Raw Dataset Schema & Volume",
      "status": "PASSED",
      "details": "5,545 records verified with all 12 expected columns."
    },
    {
      "name": "Clean Dataset Invariants",
      "status": "PASSED",
      "details": "Zero nulls, zero duplicates, all quantities >= 1, discounts strictly within [0.0, 1.0]."
    },
    {
      "name": "Financial Calculation Integrity",
      "status": "PASSED",
      "details": "Revenue: $2,961,669.95, Profit: $423,672.35. Zero instances where Profit > Sales."
    },
    {
      "name": "Customer Feature Store & Segmentation",
      "status": "PASSED",
      "details": "642 customers segmented across 5 cohorts with 100% financial reconciliation."
    },
    {
      "name": "Machine Learning Model & Inference",
      "status": "PASSED",
      "details": "Random Forest deserialized successfully. Inference verified. Test MAE: $3113.27, R2: 0.347."
    },
    {
      "name": "SQL Analytical Parity with Pandas",
      "status": "PASSED",
      "details": "100% exact numerical match across Revenue, Profit, and Order counts between SQL engine and Pandas."
    },
    {
      "name": "Technical Reports Completeness",
      "status": "PASSED",
      "details": "All 6 markdown audit and intelligence reports verified on disk."
    }
  ]
};
